name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7, 3.8, 3.9, 3.10, pypy3.7, pypy3.8, pypy3.9 ]
        poetry-version: [ 1.1.13 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    #                include:
    #                    -   os: ubuntu-latest
    #                        path: ~/.cache/pypoetry/virtualenvs
    #                    -   os: windows-latest
    #                        path: ~\AppData\Local\pypoetry\Cache\virtualenvs
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('poetry.lock') }}

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install Dependencies
        run: poetry install


      - name: Benchmark
        run: poetry run pytest --benchmark-autosave
      - name: Report
        run: poetry run python ./bench_reporter.py ./.benchmarks
