name: Benchmark
on:
  pull_request:
  push:
    branches:
      - main




jobs:
  benchmark:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", pypy-3.8, pypy-3.9,pypy-3.10, "3.11","3.12","3.13" ]
        os: [ ubuntu-latest , windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install Dependencies
        run: uv sync


      - name: Benchmark
        run: uv run pytest --benchmark-autosave

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: .benchmarks
          path: .benchmarks

  report:
    runs-on: ubuntu-latest
    needs:
      - benchmark
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Install Dependencies
        run: uv sync

      - uses: actions/download-artifact@v4

      - name: Report
        run: uv run python -m python_benchmark.bench_reporter directory-html .benchmarks .public --repo-base-url https://github.com/tmr232/python-benchmark/blob/main

      - uses: actions/upload-artifact@v4
        with:
          name: Report
          path: .public

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4
